### ISSUE TITLE
F2M does not follow yaml to execute

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus-tools#1]
Does not follow the yaml file collection_parameter: dimension: 256, while the Faiss file has dimension 128 . After creating the collectiton, the dimension is 128 instead of 256 as set in the yaml file

**Comment by shiyu22** [comment]
I tried to reproduce this issue, when I set the parameter `mode` as 'overwrite', if the dimension in the configuration file doesn't match the data, it will show an error 'The vector dimension must be equal to the collection dimension. ', but if the `mode` is 'append', if the dimension is not the same, it can be inserted successfully, which we think is reasonable.
