### ISSUE TITLE
 Failed to save if partition tag contains "/"

### ISSUE THREAD

**Issue by seo-jinBro** [milvus-io/milvus-tools#10]
Hi, I'm using "/" to use a hierarchical structure in the partition, fails to save M2H.

In save_data.py, [hdf5_filename](https://github.com/milvus-io/milvus-tools/blob/main/pymilvusdm/core/save_data.py#L20) and [yaml_filename](https://github.com/milvus-io/milvus-tools/blob/main/pymilvusdm/core/save_data.py#L54) are just created by concatenating partition_tag.

I think "/" be escaped or `os.makedir` in save_hdf5_data (not in `__init__`)

**Comment by shiyu22** [comment]
Hi, thanks for the issue, you are right and the code file you found is correct.

I think escaping the "/" would be a good idea, what do you think?

So can you submit a PR for this issue? I think it would be nice and you could be a Milvus-Tools contributor.
Also, if you don't have time to contribute, please let me know your solution and we will fix it ourselves.

**Comment by shiyu22** [comment]
Thanks @seo-jinBro  to fix this problem.
