### ISSUE TITLE
MIlvusdm issue with large scale data

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus-tools#13]
I tested Milvusdm with 100 million data, 10 million data, respectively, and when the amount of data is large, it simply does not run in small machines, summary: Milvusdm occupies a very high memory, please fix

**Comment by shiyu22** [comment]
Thanks for your issue, I have fixed it with [PR#15](https://github.com/milvus-io/milvus-tools/pull/15). And we will publish a new version later, if you want to update it immediately, you can run as follow:
```bash
$ git clone https://github.com/milvus-io/milvus-tools.git
$ echo "y" | pip uninstall pymilvusdm && python setup.py install
```
