### ISSUE TITLE
The issue about indexing data in Milvus 

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus-tools#14]
It was found that in the Milvus to Milvus process if one of the Milvus data was indexing, the transfer would be unsuccessful

**Comment by shiyu22** [comment]
You are right, Milvusdm can only import **FLAT** data or data that has been **indexed**. It is recommended to stop the source Milvus or not do anything else when using Milvusdm.

You can see in the [code](https://github.com/milvus-io/milvus-tools/blob/main/pymilvusdm/core/read_milvus_meta.py#L102) that we are reading the data when the file_type=1/7, which means it is the raw data or backup data, you can refer to [this article](https://blog.milvus.io/milvus-metadata-management-2-fields-in-the-metadata-table-3bf0d296ca6d) about the fields of metadata.
