### ISSUE TITLE
ERROR ｜ milvus_client.py ｜ insert ｜ 98 ｜ The amount of data inserted each time cannot exceed 256 MB

### ISSUE THREAD

**Issue by johntwo** [milvus-io/milvus-tools#27]
My files are 11 g in size. When I perform migration, I am prompted that the number of single inserts is too large

**Comment by shiyu22** [comment]
What's your YAML file? How is the dimension of the data?

**Comment by johntwo** [comment]
谢谢 ，已经解决了。
我的  dimension = 1024   ,迁移工具一次迁移的记录数又是10万，这么算下来一次的插入量可能达到 400m左右，所以插入失败了。
我改了下源码，就好了
![image](https://user-images.githubusercontent.com/20526955/126305541-293e8200-58ba-4363-bd1b-d67687108867.png)

**Comment by johntwo** [comment]
一次插入数量改成4万了，这个可以优化下

**Comment by shiyu22** [comment]
Maybe we can set the `batch_size` parameter to an environment variable, how do you think?

And you can modify the source code and submit a PR if you are interested, in addition, you can add `export` in the README to set it.

**Comment by johntwo** [comment]
ok
