### ISSUE TITLE
H2M No vector dimension in the log file

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus-tools#3]
2021-02-08 11:52:48,802 ｜ DEBUG ｜ data_to_milvus.py ｜ insert_data ｜ 69 ｜ Successfuly insert collection: test_bina/partition:  , total num: 5000
Only the total number of vectors, and hopefully all the information inserted in Milvus colletion can be printed

**Comment by miia12** [comment]
Thanks for your suggestion, and we'll add a dimension log in the next version. What else information you want in the log?

**Comment by jingkl** [comment]
I want to know the dimension of the vector inserted into the Milvus collection to avoid inconsistencies between the dimension inserted and the dimension configured in the yaml file
