### ISSUE TITLE
Failed  buiding wheel for pandas

### ISSUE THREAD

**Issue by TenOne506** [milvus-io/milvus-tools#68]
I tried the command pip3 install pymilvusdm to install MilvusDM, but it resulted in an error.
![image](https://github.com/user-attachments/assets/bf2ba38e-473a-4cc6-848b-b1862a5a987b)
env:
python-3.10
Milvus 2.3.10
pymilvus 2.4.3

**Comment by CongxianYang** [comment]
Hi, I'm also experiencing this problem, have you solved it yet?

**Comment by CongxianYang** [comment]
> I tried the command pip3 install pymilvusdm to install MilvusDM, but it resulted in an error. ![image](https://private-user-images.githubusercontent.com/66997415/363673858-bf2ba38e-473a-4cc6-848b-b1862a5a987b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDUzMzIsIm5iZiI6MTczMjAwNTAzMiwicGF0aCI6Ii82Njk5NzQxNS8zNjM2NzM4NTgtYmYyYmEzOGUtNDczYS00Y2M2LTg0OGItYjE4NjJhNWE5ODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzA4MjRhZjg4ZjZlZmU0MWY4N2MxZTlmMjg3ZGRmZWEwYTEyMDg0Y2I4MWNjYmY4OGU0YmI1NjliNTVkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRlVSDf3XU9_5d5REvVYgFGMMxpsu9H9HoDzNyHRHnw) env: python-3.10 Milvus 2.3.10 pymilvus 2.4.3

Hi, I'm also experiencing this problem, have you solved it yet?

**Comment by TenOne506** [comment]
> > I tried the command pip3 install pymilvusdm to install MilvusDM, but it resulted in an error. ![image](https://private-user-images.githubusercontent.com/66997415/363673858-bf2ba38e-473a-4cc6-848b-b1862a5a987b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDUzMzIsIm5iZiI6MTczMjAwNTAzMiwicGF0aCI6Ii82Njk5NzQxNS8zNjM2NzM4NTgtYmYyYmEzOGUtNDczYS00Y2M2LTg0OGItYjE4NjJhNWE5ODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzA4MjRhZjg4ZjZlZmU0MWY4N2MxZTlmMjg3ZGRmZWEwYTEyMDg0Y2I4MWNjYmY4OGU0YmI1NjliNTVkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRlVSDf3XU9_5d5REvVYgFGMMxpsu9H9HoDzNyHRHnw) env: python-3.10 Milvus 2.3.10 pymilvus 2.4.3
> 
> Hi, I'm also experiencing this problem, have you solved it yet?

no i abort it

**Comment by CongxianYang** [comment]
> > > I tried the command pip3 install pymilvusdm to install MilvusDM, but it resulted in an error. ![image](https://private-user-images.githubusercontent.com/66997415/363673858-bf2ba38e-473a-4cc6-848b-b1862a5a987b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDUzMzIsIm5iZiI6MTczMjAwNTAzMiwicGF0aCI6Ii82Njk5NzQxNS8zNjM2NzM4NTgtYmYyYmEzOGUtNDczYS00Y2M2LTg0OGItYjE4NjJhNWE5ODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzA4MjRhZjg4ZjZlZmU0MWY4N2MxZTlmMjg3ZGRmZWEwYTEyMDg0Y2I4MWNjYmY4OGU0YmI1NjliNTVkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRlVSDf3XU9_5d5REvVYgFGMMxpsu9H9HoDzNyHRHnw) env: python-3.10 Milvus 2.3.10 pymilvus 2.4.3
> > 
> > 
> > Hi, I'm also experiencing this problem, have you solved it yet?
> 
> no i abort it
Hello, do you have any other methods to migrate the milvus database to an H5 file?

**Comment by TenOne506** [comment]
> > > > I tried the command pip3 install pymilvusdm to install MilvusDM, but it resulted in an error. ![image](https://private-user-images.githubusercontent.com/66997415/363673858-bf2ba38e-473a-4cc6-848b-b1862a5a987b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDUzMzIsIm5iZiI6MTczMjAwNTAzMiwicGF0aCI6Ii82Njk5NzQxNS8zNjM2NzM4NTgtYmYyYmEzOGUtNDczYS00Y2M2LTg0OGItYjE4NjJhNWE5ODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzA4MjRhZjg4ZjZlZmU0MWY4N2MxZTlmMjg3ZGRmZWEwYTEyMDg0Y2I4MWNjYmY4OGU0YmI1NjliNTVkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRlVSDf3XU9_5d5REvVYgFGMMxpsu9H9HoDzNyHRHnw) env: python-3.10 Milvus 2.3.10 pymilvus 2.4.3
> > > 
> > > 
> > > Hi, I'm also experiencing this problem, have you solved it yet?
> > 
> > 
> > no i abort it
> > Hello, do you have any other methods to migrate the milvus database to an H5 file?

maybe you can write a python script

**Comment by CongxianYang** [comment]
> > > > > I tried the command pip3 install pymilvusdm to install MilvusDM, but it resulted in an error. ![image](https://private-user-images.githubusercontent.com/66997415/363673858-bf2ba38e-473a-4cc6-848b-b1862a5a987b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDUzMzIsIm5iZiI6MTczMjAwNTAzMiwicGF0aCI6Ii82Njk5NzQxNS8zNjM2NzM4NTgtYmYyYmEzOGUtNDczYS00Y2M2LTg0OGItYjE4NjJhNWE5ODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzA4MjRhZjg4ZjZlZmU0MWY4N2MxZTlmMjg3ZGRmZWEwYTEyMDg0Y2I4MWNjYmY4OGU0YmI1NjliNTVkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRlVSDf3XU9_5d5REvVYgFGMMxpsu9H9HoDzNyHRHnw) env: python-3.10 Milvus 2.3.10 pymilvus 2.4.3
> > > > 
> > > > 
> > > > Hi, I'm also experiencing this problem, have you solved it yet?
> > > 
> > > 
> > > no i abort it
> > > Hello, do you have any other methods to migrate the milvus database to an H5 file?
> 
> maybe you can write a python script

ok,I understand what you mean

**Comment by CongxianYang** [comment]
> > > > > > I tried the command pip3 install pymilvusdm to install MilvusDM, but it resulted in an error. ![image](https://private-user-images.githubusercontent.com/66997415/363673858-bf2ba38e-473a-4cc6-848b-b1862a5a987b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDUzMzIsIm5iZiI6MTczMjAwNTAzMiwicGF0aCI6Ii82Njk5NzQxNS8zNjM2NzM4NTgtYmYyYmEzOGUtNDczYS00Y2M2LTg0OGItYjE4NjJhNWE5ODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzA4MjRhZjg4ZjZlZmU0MWY4N2MxZTlmMjg3ZGRmZWEwYTEyMDg0Y2I4MWNjYmY4OGU0YmI1NjliNTVkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRlVSDf3XU9_5d5REvVYgFGMMxpsu9H9HoDzNyHRHnw) env: python-3.10 Milvus 2.3.10 pymilvus 2.4.3
> > > > > 
> > > > > 
> > > > > Hi, I'm also experiencing this problem, have you solved it yet?
> > > > 
> > > > 
> > > > no i abort it
> > > > Hello, do you have any other methods to migrate the milvus database to an H5 file?
> > 
> > 
> > maybe you can write a python script
> 
> ok,I understand what you mean

I found the solution, python version is too high cause.
 I can build successfully with python=3.7 environment.
you can try

**Comment by touale** [comment]
> > > > > > > I tried the command pip3 install pymilvusdm to install MilvusDM, but it resulted in an error. <img alt="image" width="44" height="21" src="https://private-user-images.githubusercontent.com/66997415/363673858-bf2ba38e-473a-4cc6-848b-b1862a5a987b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDUzMzIsIm5iZiI6MTczMjAwNTAzMiwicGF0aCI6Ii82Njk5NzQxNS8zNjM2NzM4NTgtYmYyYmEzOGUtNDczYS00Y2M2LTg0OGItYjE4NjJhNWE5ODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzA4MjRhZjg4ZjZlZmU0MWY4N2MxZTlmMjg3ZGRmZWEwYTEyMDg0Y2I4MWNjYmY4OGU0YmI1NjliNTVkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KRlVSDf3XU9_5d5REvVYgFGMMxpsu9H9HoDzNyHRHnw"> env: python-3.10 Milvus 2.3.10 pymilvus 2.4.3
> > > > > > 
> > > > > > 
> > > > > > Hi, I'm also experiencing this problem, have you solved it yet?
> > > > > 
> > > > > 
> > > > > no i abort it
> > > > > Hello, do you have any other methods to migrate the milvus database to an H5 file?
> > > 
> > > 
> > > maybe you can write a python script
> > 
> > 
> > ok,I understand what you mean
> 
> I found the solution, python version is too high cause. I can build successfully with python=3.7 environment. you can try

It really works
