### ISSUE TITLE
Data integrity

### ISSUE THREAD

**Issue by liuzhiliangpc** [milvus-io/milvus-tools#8]
When I transform data of milvus, some  situations  happend which some vectors can not find in new milvus.
origin milvus:
version=0.10.4,
index_type=IndexType.IVF_FLAT
index_param={'nlist': 16384}

new milvus:
version=1.0.0,
index_type=IndexType.IVF_FLAT
index_param={'nlist': 16384}

**Comment by shiyu22** [comment]
This is a bug in the index data of milvusdmv0.1, we have fixed it in the latest code.

So you need to clone the main project, then uninstall the milvusdm0.1 and reinstall with the source code:
1. git clone https://github.com/milvus-io/milvus-tools.git
2. echo "y" | pip uninstall milvusdm && python setup.py install

And if you want to migrate data from milvus0.10.x to milvus1.0, you need to reinstall pymilvus==1.0.1.

**Comment by liuzhiliangpc** [comment]
Thank you！
